// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// GetCounter provides a mock function with given fields: _a0, key
func (_m *Store) GetCounter(_a0 context.Context, key string) (int, error) {
	ret := _m.Called(_a0, key)

	if len(ret) == 0 {
		panic("no return value specified for GetCounter")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(_a0, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(_a0, key)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementCounter provides a mock function with given fields: _a0, key, exp
func (_m *Store) IncrementCounter(_a0 context.Context, key string, exp time.Duration) {
	_m.Called(_a0, key, exp)
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
